source 'https://rubygems.org'

# Core gems
gem 'chronic'
gem 'cpt_hook'
gem 'cucumber', '~> 3.0'
gem 'cuke_cataloger'
gem 'data_magic'
gem 'magic_path' # Not locked yet due to active development
gem 'mail'
gem 'page-object'
gem 'relish'
gem 'require_all'
gem 'rb-readline'
gem 'rspec'
gem 'sauce_whisk'
gem 'spreadsheet'
gem 'trollop'
gem 'twilio-ruby'
gem 'watir', '>=6.16' # has new scrolling feature #, '~> 6.10.3'
gem 'watir_angular'
gem 'webdrivers'

# Mobile testing
gem 'appium_lib'

# Development / Debugging
gem 'pry'
gem 'pry-byebug'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'rake'
gem 'yard'
gem 'yard-cucumber'

# Tools to keep our code quality up
gem 'overcommit'
gem 'rubocop'

# Useful gems
gem 'facets'
gem 'nenv'

# Video Recording
# Need FFI Gem on Windows
if RUBY_PLATFORM.match?(/mingw/) || RUBY_PLATFORM.match?(/win/)
  gem 'ffi'
end
gem 'screen-recorder'
