import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "./components/header";
import { Locale } from "@/i18n-config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header lang={lang} />
        <main className="max-w-screen-2xl m-auto">{children}</main>
      </body>
    </html>
  );
}
